name: Deploy Workflow

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy Demo
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy
        run: |
          curl -XPOST -u "${{secrets.DEPLOY_USER}}:${{secrets.DEPLOY_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/stepan-anokhin/stepan-anokhin.github.io/dispatches --data '{"event_type": "deploy_spb_histmap"}'
